export const GET_NOTE_BY_ID = 'DETAIL/GET_NOTE_BY_ID';
export const SET_NOTE = 'DETAIL/SET_NOTE';
export const UPDATE_NOTE = 'DETAIL/UPDATE_NOTE';
export const DELETE_NOTE = 'DETAIL/DELETE_NOTE';
export const SET_LOADING = 'DETAIL/SET_LOADING';
